version: '3'
services:
  microservice:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${DOCKER_PORTS}
    environment:
      - spring.datasource.url=${DATASOURCE_DOCKER_URL}
      - spring.datasource.username=${DATASOURCE_USERNAME}
      - spring.datasource.password=${DATASOURCE_PASSWORD}
    restart: always'
